version: '3.8'

services:
  gateway:
    build: .
    container_name: gateway-server
    command: java -cp bin com.foodordering.gateway.GatewayServer
    network_mode: host
    depends_on:
      - node1
      - node2
      - node3

  node1:
    build: .
    container_name: order-node-1
    command: java -cp bin com.foodordering.node.OrderNodeServer 1 PRIMARY 1101
    network_mode: host
    volumes:
      - ./data/node1:/app/data/node1

  node2:
    build: .
    container_name: order-node-2
    command: java -cp bin com.foodordering.node.OrderNodeServer 2 BACKUP 1102
    network_mode: host
    volumes:
      - ./data/node2:/app/data/node2

  node3:
    build: .
    container_name: order-node-3
    command: java -cp bin com.foodordering.node.OrderNodeServer 3 BACKUP 1103
    network_mode: host
    volumes:
      - ./data/node3:/app/data/node3

  customer:
    build: .
    container_name: customer-client
    command: java -cp bin com.foodordering.client.customer.CustomerClient
    network_mode: host
    profiles: ["client"]

  rider:
    build: .
    container_name: rider-client
    command: java -cp bin com.foodordering.client.rider.RiderClient R1
    network_mode: host
    profiles: ["client"]